import{i as c,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d=n=>n.map(({webformatURL:o,largeImageURL:t,tags:s,likes:e,views:r,comments:i,downloads:m})=>`<a href="${t}" class="gallery-item">
        <div class = "img-card">
          <img src="${o}" alt="${s}" loading="lazy" />
          <div class="img-info">
            <p class="img-info-item">Likes<span>${e}</span></p>
            <p class="img-info-item">Views<span>${r}</span></p>
            <p class="img-info-item">Comments<span>${i}</span></p>
            <p class="img-info-item">Downloads<span>${m}</span></p>
          </div>
          </div>
        </a>`).join(""),f="48239935-17beded8a236fb1397b75b1c0",y="https://pixabay.com/api/";function g(n){const o=`${y}?key=${f}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()}).catch(t=>{throw console.error("Error fetching images;",t),t})}const l=document.querySelector(".search-form"),h=document.querySelector(".search-input"),u=document.querySelector(".gallery"),a=document.querySelector(".load");a.style.display="none";function b(n){n.preventDefault(),u.innerHTML="",a.style.display="block";const o=h.value.trim();if(o===""){a.style.display="none",c.warning({title:"Warning",message:"Please enter a search query!"});return}g(o).then(t=>{if(a.style.display="none",t.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),l.reset();return}const s=d(t.hits);u.insertAdjacentHTML("beforeend",s),new p(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250}).refresh(),l.reset()}).catch(()=>{c.error({title:"Error",message:"Failed to load images. Please try again later."})})}l.addEventListener("submit",b);
//# sourceMappingURL=index.js.map
