var b=e=>{throw TypeError(e)};var L=(e,t,r)=>t.has(e)||b("Cannot "+r);var p=(e,t,r)=>(L(e,t,"read from private field"),r?r.call(e):t.get(e)),m=(e,t,r)=>t.has(e)?b("Cannot add the same private member more than once"):t instanceof WeakSet?t.add(e):t.set(e,r),P=(e,t,r,a)=>(L(e,t,"write to private field"),a?a.call(e,r):t.set(e,r),r);import{a as D,i,S as q}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const v=e=>e.map(({webformatURL:t,largeImageURL:r,tags:a,likes:s,views:o,comments:d,downloads:$})=>`<a href="${r}" class="gallery-item">
        <div class = "img-card">
          <img src="${t}" alt="${a}" loading="lazy" />
          <div class="img-info">
            <p class="img-info-item">Likes<span>${s}</span></p>
            <p class="img-info-item">Views<span>${o}</span></p>
            <p class="img-info-item">Comments<span>${d}</span></p>
            <p class="img-info-item">Downloads<span>${$}</span></p>
          </div>
          </div>
        </a>`).join("");var h,g,y;class H{constructor(){m(this,h,"48239935-17beded8a236fb1397b75b1c0");m(this,g,"https://pixabay.com/api/");m(this,y,"")}async fetchPhotos(t,r){const a=`${p(this,g)}?key=${p(this,h)}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const{data:s}=await D.get(a);return s}catch(s){throw console.error("Error fetching images;",s),s}}set query(t){P(this,y,t)}get query(){return p(this,y)}}h=new WeakMap,g=new WeakMap,y=new WeakMap;const w=document.querySelector(".search-form"),M=document.querySelector(".search-input"),f=document.querySelector(".gallery"),n=document.querySelector(".load");document.addEventListener("DOMContentLoaded",()=>{n.style.display="none"});const u=document.querySelector(".load-more-btn"),E=new H;let l=1,S="",c;async function O(e){try{e.preventDefault(),f.innerHTML="",n.style.display="block",l=1,u.style.display="none";const t=M.value.trim();if(S=t,t===""){n.style.display="none",i.warning({title:"Warning",message:"Please enter a search query!"});return}u.classList.add("is-hidden");const r=await E.fetchPhotos(t,l);if(n.style.display="none",!r.hits||r.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}f.insertAdjacentHTML("beforeend",v(r.hits)),c?c.refresh():c=new q(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250}),i.success({title:"Success",message:`Found ${r.totalHits} images!`}),r.totalHits>l*15&&(u.style.display="block")}catch{i.error({title:"Error",message:"Failed to load images. Please try again later."})}finally{w.reset()}}async function A(){l+=1;try{n.style.display="block";const e=await E.fetchPhotos(S,l);e.hits&&e.hits.length>0?(C(e.hits),l*15>=e.totalHits&&(i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),u.style.display="none")):i.error({title:"Error",message:"No more images found."})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{n.style.display="none"}}function C(e){const t=v(e);f.insertAdjacentHTML("beforeend",t),c?c.refresh():c=new q(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250});const{height:r}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}w.addEventListener("submit",O);u.addEventListener("click",A);
//# sourceMappingURL=index.js.map
