var b=e=>{throw TypeError(e)};var L=(e,t,r)=>t.has(e)||b("Cannot "+r);var y=(e,t,r)=>(L(e,t,"read from private field"),r?r.call(e):t.get(e)),m=(e,t,r)=>t.has(e)?b("Cannot add the same private member more than once"):t instanceof WeakSet?t.add(e):t.set(e,r),P=(e,t,r,a)=>(L(e,t,"write to private field"),a?a.call(e,r):t.set(e,r),r);import{a as $,i,S as H}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const q=e=>e.map(({webformatURL:t,largeImageURL:r,tags:a,likes:s,views:o,comments:c,downloads:S})=>`<a href="${r}" class="gallery-item">
        <div class = "img-card">
          <img src="${t}" alt="${a}" loading="lazy" />
          <div class="img-info">
            <p class="img-info-item">Likes<span>${s}</span></p>
            <p class="img-info-item">Views<span>${o}</span></p>
            <p class="img-info-item">Comments<span>${c}</span></p>
            <p class="img-info-item">Downloads<span>${S}</span></p>
          </div>
          </div>
        </a>`).join("");var f,h,u;class M{constructor(){m(this,f,"48239935-17beded8a236fb1397b75b1c0");m(this,h,"https://pixabay.com/api/");m(this,u,"")}async fetchPhotos(t,r){const a=`${y(this,h)}?key=${y(this,f)}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const{data:s}=await $.get(a);return s}catch(s){throw console.error("Error fetching images;",s),s}}set query(t){P(this,u,t)}get query(){return y(this,u)}}f=new WeakMap,h=new WeakMap,u=new WeakMap;const v=document.querySelector(".search-form"),O=document.querySelector(".search-input"),p=document.querySelector(".gallery"),n=document.querySelector(".load");document.addEventListener("DOMContentLoaded",()=>{n.style.display="none"});const d=document.querySelector(".load-more-btn"),w=new M;let l=1,E="",g;async function A(e){try{e.preventDefault(),p.innerHTML="",n.style.display="block",l=1,d.style.display="none";const t=O.value.trim();if(E=t,t===""){n.style.display="none",i.warning({title:"Warning",message:"Please enter a search query!"});return}d.classList.add("is-hidden");const r=await w.fetchPhotos(t,l);if(n.style.display="none",!r.hits||r.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}p.insertAdjacentHTML("beforeend",q(r.hits)),i.success({title:"Success",message:`Found ${r.totalHits} images!`}),r.totalHits>l*15&&(d.style.display="block")}catch{i.error({title:"Error",message:"Failed to load images. Please try again later."})}finally{v.reset()}}async function C(){l+=1;try{n.style.display="block";const e=await w.fetchPhotos(E,l);e.hits&&e.hits.length>0?(D(e.hits),l*15>=e.totalHits&&(i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),d.style.display="none")):i.error({title:"Error",message:"No more images found."})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{n.style.display="none"}}function D(e){const t=q(e);p.insertAdjacentHTML("beforeend",t),g?g.refresh():g=new H(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250});const{height:r}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}v.addEventListener("submit",A);d.addEventListener("click",C);
//# sourceMappingURL=index.js.map
